apiVersion: v1
kind: Namespace
metadata:
  name: sre-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-ecs-web
  namespace: sre-lab
  labels:
    app: sre-ecs-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-ecs-web
  template:
    metadata:
      labels:
        app: sre-ecs-web
    spec:
      containers:
        - name: sre-ecs-web
          image: 728121070699.dkr.ecr.us-east-2.amazonaws.com/sre-ecs-web:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sre-ecs-web-service
  namespace: sre-lab
spec:
  type: ClusterIP
  selector:
    app: sre-ecs-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080